name: destinaku
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Cached network image
  cached_network_image: ^3.3.0

  # Fetch Data From Api
  dio: ^5.4.0

  # Handle Success/Error State From Data Source
  dartz: ^0.10.1

  # Device preview to test app in all devices
  device_preview: ^1.2.0

  # Being able to compare objects in Dart
  equatable: ^2.0.5

  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1

  # Make Pages Responsive To All Devices
  flutter_screenutil: ^5.9.3

  # Svg Image
  flutter_svg: ^2.0.9

  # BloC State Management
  flutter_bloc: ^8.1.3

  # Code generation
  # freezed: ^2.4.5

  # Dependency Injection
  get_it: ^7.6.4

  # routing navigation
  go_router: ^14.2.1

  # For Localization
  intl: ^0.19.0

  # Json Annotation
  json_annotation: ^4.8.1

  # Logging Interceptor
  logging: ^1.2.0

  # To Store Data In Local Storage
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # for generate intl
  # flutter pub run intl_utils:generate
  intl_utils: ^2.8.7

  # To generate Localization File's
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  # Localization config
  flutter_localizations:
    sdk: flutter

# Localization config
flutter_intl:
  main_locale: en
  enabled: true
  output_dir: lib/src/core/translations
  arb_dir: lib/src/core/translations

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/images/auth/
    - assets/images/icons/
  
  fonts:
    - family: Mulish-Bold
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
    - family: Mulish-Medium
      fonts:
        - asset: assets/fonts/Mulish-Medium.ttf
    - family: Mulish-Regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: Mulish-SemiBold
      fonts:
        - asset: assets/fonts/Mulish-SemiBold.ttf
        